# Generated by Django 5.2.6 on 2025-10-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('terjual', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('jml_pemesanan', models.PositiveIntegerField()),
                ('alamat', models.TextField()),
                ('nama_product', models.CharField(max_length=100)),
                ('status_pemesanan', models.CharField(choices=[('pending', 'Pending'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='pending', max_length=20)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('umur', models.PositiveIntegerField()),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='dashboard.product')),
            ],
        ),
    ]
