# Generated by Django 5.2.6 on 2025-11-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pemesanan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
