# Generated by Django 5.2.6 on 2025-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_product_id_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
