# Generated by Django 5.2.6 on 2025-11-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_alter_order_buyer_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_birth',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
