# Generated by Django 5.2.6 on 2025-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_buyer_birth_order_buyer_age_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Other', max_length=10),
        ),
    ]
